dist: trusty
sudo: false
language: php

install:
  - if [[ $TRAVIS_PHP_VERSION == "hhvm" ]]; then
      composer global require squizlabs/PHP_CodeSniffer;
    else
      pear channel-update pear.php.net;
      pear install PHP_CodeSniffer;
    fi

script:
  - phpenv rehash
  - if [[ $TRAVIS_PHP_VERSION == "hhvm" ]]; then
      /home/travis/.composer/vendor/bin/phpcs . --standard=phpcs.xml --warning-severity=0 --extensions=php -p;
    else
      phpcs . --standard=phpcs.xml --warning-severity=0 --extensions=php -p;
    fi

matrix:
  fast_finish: true

  include:
    - php: 5.6
    - php: 7.0
    - php: hhvm
    - php: nightly

  allow_failures:
    - php: hhvm
    - php: nightly
